### ISSUE TITLE
bot.eaten is not updated

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#599] opened 2019-06-16 16:31 UTC
`bot.eaten` is not updated anymore...

**Comment by Debilski** [comment] 2019-06-16 18:51
Please explain what the problem is. We have a test for `bot.eaten` behaviour in https://github.com/ASPP/pelita/blob/pelita-core-2.0/test/test_team.py#L294

**Comment by otizonaizit** [comment] 2019-06-16 19:18
Running detect death demo players from pelita_template fails, and the debugger shows that bot.eaten is not set after the bot gets eaten.

**Comment by Debilski** [comment] 2019-06-16 20:05
The current behaviour is that when bot 0 is killed by bot 1, then bot 2 will notice it as `bot.other.eaten`, but then again when it is 0’s turn, the flag has been reset. I’m a little undecided what should be the correct behaviour, but in a way this is the approach with the fewest edge cases to it. The flag is presented to the user just once and immediately after the kill happened.

Example: https://gist.github.com/Debilski/f938eb6a7b5ccf7d858a76f862a19add

**Comment by otizonaizit** [comment] 2019-06-16 20:55
The detect death demo was working before though. Proposal:
 bot.eaten = [bool, bool]
and the corresponding item (0 for turn 0 and 1 for turn 1) gets reset at the next round at the same turn, so that the eaten bot himself has a chance to see it.

**Comment by Debilski** [comment] 2019-06-17 08:15
Yeah, I think in the older behaviour, we had the flag set for longer. I don’t remember anymore if this was technical or if we had made it a conscious decision.

What would be the advantage of having a list? I.e. why `bot.eaten[bot.turn]` instead of just `bot eaten`? (I assume that in the list case `bot.eaten == bot.other.eaten`, right?)

Alternatively, we could introduce `bot.times_eaten` (a kill count per bot), which will have the user to store the last eaten count and manually check whether it has increased but which will be obvious all the time.

**Comment by otizonaizit** [comment] 2019-06-17 08:23
The more I think about it, the more I think that the most intuitive API would be that bot.eaten means "Has the current bot been eaten since the last time it has been called, i.e. has it been eaten in the previous round?". So bot.eaten should survive until the affected bot is called again in the next round.
bot.other.eaten means "has the other bot in my team been eaten since the last time I was called, i.e. has the other bot been eaten in this or the previous round?".

If you look at the code in death detector in pelita_template it's pretty clear that this is the assumed meaning of the flag in the code. It is not clear to me if the necessary change is dependent on your refactoring of RemoteTeam or not.

**Comment by Debilski** [comment] 2019-06-17 08:41
To me the non-obvious behaviour comes when one wants to write a move function that checks whether either bot has been eaten and adapts the behaviour. This then leads to the situation that a death is detected twice when it shown once for `bot.other` and in the next turn for `bot`. Resolving this on the user side is harder than the other way round.

Of course we can change the behaviour (in `Team` – `RemoteTeam` is unrelated) again, but it would be quite easy to also fix the death detector demo:


    # check if one of our bots has been eaten in the previous step
    for b in (bot, bot.other):
        # set the speak inertia
        if b.eaten:
            state[b.turn] = EATEN_INERTIA

(Probably nicer without a for loop for naming reasons.)

**Comment by otizonaizit** [comment] 2019-06-17 08:46
On Mon 17 Jun, 01:41 -0700, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>To me the non-obvious behaviour comes when one wants to write a move function that checks whether either bot has been eaten and adapts the behaviour. This then leads to the situation that a death is detected twice when it shown once for `bot.other` and in the next turn for `bot`. Resolving this on the user side is harder than the other way round.
Can you write an example bot that does it? I don't understand why you would detect it twice.

>Of course we can change the behaviour (in `Team` – `RemoteTeam` is unrelated) again, but it would be quite easy to also fix the death detector demo:
>
> # check if one of our bots has been eaten in the previous step
> for b in (bot, bot.other):
> # set the speak inertia
> if b.eaten:
> state[b.turn] = EATEN_INERTIA

But this is wrong. Only the bot that has been indeed eaten should say "I am a zombie" now. Not that to make it work correctly you need some gimmicks, because you would have to store bot.other.eaten so that when the killed bot is reborn again has a chance to know that it was killed.

The code as it is now is intuitive and would just work if we use the interpretation I wrote in the previous comment.

**Comment by lschwetlick** [comment] 2019-06-17 08:50
Why don't we have it as a list of two booleans, one for each bot?

**Comment by otizonaizit** [comment] 2019-06-17 08:58
This is the only other option which makes sense, if you don't like the bot.eaten spelling I introduced above. With the list, the code in detect death would look like:

```python
if bot.eaten[turn]:
    ...
```

as opposed to:

```python
if bot.eaten:
    ...
```
With the list there is also the fact that we introduce an attribute which contains state for the `other` bot directly under the `bot` namespace, whereas now we have it cleanly separated, in the sense that stuff related to `bot.other` is stored in `bot.other.xxx`.

**Comment by Debilski** [comment] 2019-06-17 10:32
>>     # check if one of our bots has been eaten in the previous step
>>     for b in (bot, bot.other):
>>         # set the speak inertia
>>         if b.eaten:
>>             state[b.turn] = EATEN_INERTIA

> But this is wrong. Only the bot that has been indeed eaten should say "I am a zombie" now.

That is exactly what is happening. No further changes needed. It is a nice way to show that we can set the state of the other bot, even though the bot is not currently active

**Comment by otizonaizit** [comment] 2019-06-17 11:35
On Mon 17 Jun, 03:32 -0700, Rike-Benjamin Schuppner <notifications@github.com> wrote:
>>But this is wrong. Only the bot that has been indeed eaten should say "I am a zombie" now.
>
>That is exactly what is happening. No further changes needed. It is a nice way to show that we can set the state of the other bot, even though the bot is not currently active

OK, it works. But it is confusing. And the fact that you can set the state of the other bot is a side-effect of how things work now, but I don't think it should be supported. Setting attributes on the other bot does not do anything for all other attributes. I do not think we should show that it works. I stand by my point: either bot.eaten survives for one round or we use the list solution.

**Comment by Debilski** [comment] 2019-06-17 11:40
Example: https://gist.github.com/Debilski/bd13a675755c6ef65e1667b3333f8e50

We have a naive bot implementation, that wants our team to go into alert mode (whatever that is) once one of the bots has been eaten. Additionally, we want to count the total number of times that we have been killed, so it seems obvious to do that in the same loop.

For both the current API and your proposed change, we have two `run_game` methods. In the first one, we get killed by bot 1, in the second by bot 3.

My issue is that our quite obvious code gives the wrong result in the last example and it is a) not obvious to detect that this has happened (because it only appears in 50% of the cases) and b) involves more code to untangle than the other way round. If a user wants to store the eaten flag for longer, they can just put it into their state dict. We can give an example for that and it is obvious. (And for us it means having one thing less to worry about in our own `Team` code ;) .)

**Comment by Debilski** [comment] 2019-06-17 11:42
Still not sure I get it but the list behaviour would be exactly the same, no?

**Comment by Debilski** [comment] 2019-06-17 11:43
And my proposal is not to set attributes on the other bot. That is not going to work. Of course you want to interact with `state`.

**Comment by otizonaizit** [comment] 2019-06-17 11:54
Your example can be rewritten in a way that transmits the intent of the code more clearly, IMHO, like this:
https://gist.github.com/otizonaizit/08a65374258dc3c6f9dd5a1bad11d09d

(and still be compatible with my proposal, which, by the way, is the way it was working before, so I see the change as arbitrary and do not get why we are having the discussion at all ;))

**Comment by Debilski** [comment] 2019-06-17 18:00
If you just write a five-word issue with no other info, of course you’ll get a discussion. ;)

I mean, we wrote the API last year very very quickly just before the school (`bot.eaten` was a big hack and we have never really cared about this attribute before anyway), I think now we can take some time to revisit and acknowledge the bad decisions we may have made back then. :)

**Closed** 2019-07-24 14:57 UTC
