### ISSUE TITLE
Allow Greek script in team names.

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#409] opened 2017-08-25 10:02 UTC

**Comment by Debilski** [comment] 2017-08-25 10:11
Currently the check is in pelita/scripts/pelita_player.py anyway, which means that it is basically a client-side check. The main pelita process will try to interpret anything that is sent over json.

We should either fix it in main pelita as well or lift the restriction.

**Comment by Debilski** [comment] 2018-08-25 10:44
I think this was solved in ac22c8d966fd52a11f85fd241ed5b7f0bceab2f3 .

**Comment by Debilski** [comment] 2018-08-25 10:47
Ah, no. It still exists.

**Comment by otizonaizit** [comment] 2019-02-04 17:23
Semi-duplicate of #511

**Closed by otizonaizit** 2019-02-04 17:23 UTC
Labels: Gameplay/Rules, Meta
