### ISSUE TITLE
bot.homezone contains walls

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#759] opened 2023-07-01 18:43 UTC
The attribute `bot.homezone` contains all coordinates on the left or the right of the maze, including the walls. If the students use it, they tend to assume that it contains only valid positions, which I think is a reasonable assumption.

I think we should change the attribute to report only valid position. Testing if a wall is in your homezone or that of the enemy is not really useful.

**Comment by Debilski** [comment] 2023-07-01 18:56
Duplicate of #688

**Comment by otizonaizit** [comment] 2023-07-01 19:03
the fact that this issue came up again seems to indicate that we need to fix ASAP.

**Closed** 2023-08-04 12:47 UTC
